[package]
name = "scd30"
version = "0.1.0"
authors = ["Jorge Aparicio <jorge.aparicio@ferrous-systems.com>"]
edition = "2018"

[dependencies]
embedded-hal = "0.2.4"
crc-any = { version = "2.3.5", default-features = false }
defmt = "0.2.0"

[dev-dependencies]
embedded-hal-mock = "0.7.2"
